package:
  name: pynio
  version: "1.4.3"

source:
  git_url: https://github.com/NCAR/pynio.git
  git_rev: 1.4.3

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libpng 
    - jasper
    - jpeg
    - zlib
    - hdf4
    - hdf5
    - numpy x.x
    - gcc
    - python
    - libnetcdf
    - proj4
    - hdfeos2
    - g2clib
    - libgdal
    - libiconv
    - hdfeos5 
    - curl

  run:
    - libgcc
    - libpng
    - jasper
    - jpeg
    - zlib
    - numpy x.x
    - python
    - libnetcdf
    - hdf5
    - hdf4
    - proj4
    - hdfeos2
    - g2clib
    - libgdal
    - libiconv
    - hdfeos5
    - curl

test:
  requires:
    - nose
  imports:
    - Nio
  commands:
    - cd $SRC_DIR/test && for file in `cat testfiles`; do echo $file ; nosetests $file ; done |tee pynio-test.log

